kafka:
  bootstrap-servers: localhost:9092
  bwr-topic-name: bwr-topic
  group-id: bwr-group-id

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: Test.123
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    table: flyway_schema_history
    url: jdbc:mysql://localhost:3306/
    user: root
    password: Test.123
    locations: classpath:db/migration
    schemas: bwr

quartz:
  properties:
    #============================================================================
    # Configure Main Scheduler Properties
    #============================================================================
    org.quartz.scheduler.instanceName: bwr-job-scheduler
    org.quartz.scheduler.instanceId: AUTO

    #============================================================================
    # Configure ThreadPool
    #============================================================================
    org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
    org.quartz.threadPool.threadCount: 25
    org.quartz.threadPool.threadPriority: 5

    #============================================================================
    # Configure JobStore
    #============================================================================
    org.quartz.jobStore.misfireThreshold: 1000
    org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
    org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    org.quartz.jobStore.dataSource: quartz
    org.quartz.jobStore.tablePrefix: QRTZ_

    #============================================================================
    # Configure DataSource
    #============================================================================
    org.quartz.dataSource.quartz.provider: hikaricp
    org.quartz.dataSource.quartz.driver: com.mysql.cj.jdbc.Driver
    org.quartz.dataSource.quartz.URL: jdbc:mysql://localhost:3306/bwr
    org.quartz.dataSource.quartz.user: root
    org.quartz.dataSource.quartz.password: Test.123


    #============================================================================
    # Configure Cluster properties
    #============================================================================
    org.quartz.jobStore.isClustered: true
    org.quartz.jobStore.clusterCheckinInterval: 1000