server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092
  topic-name: bwr-topic
  group-id: bwr-group-id

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: Test.123
    driver-class-name: com.mysql.cj.jdbc.Driver

robot-id: 1
