server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092
  task:
    topic-name: task-topic
    group-id: bwr-robot-task-group-id
  ack:
    topic-name: ack-topic
  keep-alive:
    topic-name: keep-alive-topic
  concurrency: 3

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: Test.123
    driver-class-name: com.mysql.cj.jdbc.Driver

robot-id: 1
