package com.example.bwr.enums;

public enum ActionType {
  UPLOAD_TASK, START_COMMAND, START_COMMAND_ACK, STOP_COMMAND,
  STOP_COMMAND_ACK, END_TASK, END_TASK_ACK, TURN_ON_ROBOT,
  TURN_ON_ROBOT_ACK, TURN_OFF_ROBOT, KEEP_ALIVE
}
